version: '3'
services:
  proxy:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - redis
    environment:
    - PROXY_PORT=4000
    - REDIS_ADDRESS=redis:6379
    - CACHE_EXPIRY_SECONDS=4
    - CACHE_CAPACITY=2
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  integration-tests:
    build:
      context: ./redis-proxy-integration-tests
    environment:
      - REDIS_ADDRESS=redis:6379
      - PROXY_HOST=proxy
      - PROXY_PORT=4000
    depends_on:
      - redis
      - proxy